chore(main): refactor out archiving and binary listing
* Added tests for these features
* Add test runner to pipeline

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -34,3 +34,23 @@ jobs:
         uses: golangci/golangci-lint-action@639cd343e1d3b897ff35927a75193d57cfcba299 # v3.6.0
         with:
           version: latest
+
+      - name: Install tparse
+        run: go install github.com/mfridman/tparse@latest
+
+      - name: Test
+        env:
+          COVER_OPTS: "-coverprofile=coverage.txt -covermode=atomic"
+          GOFLAGS:  "-v -count=1 -json"
+        run: go test $COVER_OPTS ./... | tparse -all -notests -format markdown >> $GITHUB_STEP_SUMMARY
+
+      - name: Verify git clean
+        shell: bash
+        run: |
+          if [[ -z "$(git status --porcelain)" ]]; then
+            echo "${{ github.repository }} up to date."
+          else
+            echo "${{ github.repository }} is dirty."
+            echo "::error:: $(git status)"
+            exit 1
+          fi
